'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Dashboard

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''ToolkitScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ToolkitScriptManager1 As Global.AjaxControlToolkit.ToolkitScriptManager

    '''<summary>
    '''hidPeriodTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidPeriodTo As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidRequestDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidRequestDate As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidRequestor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidRequestor As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidEffectiveDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidEffectiveDate As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidExpiryDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidExpiryDate As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidStatus As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidCurrentApprover control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidCurrentApprover As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidOriginComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidOriginComment As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidAccessibleModules control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidAccessibleModules As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidCallback control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidCallback As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPeriodFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPeriodFrom As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPeriodFrom_CalendarExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPeriodFrom_CalendarExtender As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''txtPeriodTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPeriodTo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPeriodTo_CalendarExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPeriodTo_CalendarExtender As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''mainDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mainDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''mainDiv2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mainDiv2 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''tb1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb1 As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''linkOpenRequests control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents linkOpenRequests As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''linkInDiscussionStationRequests control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents linkInDiscussionStationRequests As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''linkInDiscussionClientRequests control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents linkInDiscussionClientRequests As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''linkApprovedRequests control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents linkApprovedRequests As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''linkRejectedRequests control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents linkRejectedRequests As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lblOpenToAllRequests control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOpenToAllRequests As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblInDiscussionStationRequests control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInDiscussionStationRequests As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblInDiscussionClientRequests control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInDiscussionClientRequests As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblApprovedRequests control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblApprovedRequests As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRejectedRequests control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRejectedRequests As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''linkOpenToMeRequests control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents linkOpenToMeRequests As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''linkInDiscussionInLoopStationRequests control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents linkInDiscussionInLoopStationRequests As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''linkInDiscussionInLoopClientRequests control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents linkInDiscussionInLoopClientRequests As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''linkApprovedInLoopRequests control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents linkApprovedInLoopRequests As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''linkRejectedInLoopRequests control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents linkRejectedInLoopRequests As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lblOpenToMeRequests control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOpenToMeRequests As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblInDiscussionInLoopStationRequests control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInDiscussionInLoopStationRequests As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblInDiscussionInLoopClientRequests control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInDiscussionInLoopClientRequests As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblApprovedInLoopRequests control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblApprovedInLoopRequests As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRejectedInLoopRequests control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRejectedInLoopRequests As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSummaryStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSummaryStatus As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gridRateRequestGroupings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridRateRequestGroupings As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''SqlDataSource1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource1 As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''tb2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb2 As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''lblStatusTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStatusTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gridRateRequests control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridRateRequests As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''SqlDataSource3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource3 As Global.System.Web.UI.WebControls.SqlDataSource
End Class
